# Generated by Django 3.2.13 on 2023-12-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=25)),
                ('time_elapsed', models.IntegerField(default=0)),
            ],
        ),
    ]
