# Generated by Django 3.2.13 on 2023-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodromo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=25)),
                ('seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PomodoroSession',
        ),
    ]
