# Generated by Django 3.2.13 on 2023-12-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodromo', '0002_auto_20231209_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='uuid',
            field=models.IntegerField(default=0),
        ),
    ]
