# Generated by Django 3.2.13 on 2023-12-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodromo', '0003_timers_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
