# Generated by Django 3.2.13 on 2023-12-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodromo', '0004_timers_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timers',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
